api_root_path: ''
auto_reload: false
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
docs_url: /docs
file_deletion_request_topic: file-deletion-requests
file_deletion_request_type: file_deletion_requested
host: 127.0.0.1
kafka_servers:
  - kafka:9092
openapi_url: /openapi.json
port: 8080
service_instance_id: "1"
service_name: pcs
workers: 1

token_hashes: [abcdef, ghijkl]
mongo_dsn: "mongodb://mongodb:27017"
db_name: "dev"
