components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  description: A service exposing an external API to commission file deletionsfrom
    the wholefile backend.
  title: Purge Controller Service
  version: 3.0.1
openapi: 3.1.0
paths:
  /files/{file_id}:
    delete:
      operationId: deleteFile
      parameters:
      - in: query
        name: args
        required: true
        schema:
          title: Args
      - in: query
        name: kwargs
        required: true
        schema:
          title: Kwargs
      responses:
        '202':
          content:
            application/json:
              schema: {}
          description: Commissioned file deletion
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Deletes the corresponding file.
      tags:
      - PurgeControllerService
  /health:
    get:
      operationId: traced_function_health_get
      parameters:
      - in: query
        name: args
        required: true
        schema:
          title: Args
      - in: query
        name: kwargs
        required: true
        schema:
          title: Kwargs
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: health
      tags:
      - PurgeControllerService
tags:
- name: PurgeControllerService
