service_name: fis
private_key_path: ./placeholder.sec
token_hashes: [abcdef, ghijkl]

file_interrogations_topic: file-interrogations
interrogation_success_type: file_interrogation_success

service_instance_id: '1'
kafka_servers: ["kafka:9092"]

vault_url: "http://127.0.0.1:8200"
vault_role_id: dummy-role
vault_secret_id: dummy-secret
vault_verify: True
vault_path: ekss
vault_secrets_mount_point: secret
vault_kube_role: dummy-role
mongo_dsn: "mongodb://mongodb:27017"
db_name: "dev"
migration_wait_sec: 10
db_version_collection: fisDbVersions

otel_exporter_endpoint: http://localhost:4318
