db_connection_str: "mongodb://mongodb:27017"
db_name: "dev"
object_storages:
  test:
    bucket: permanent
    credentials:
      s3_endpoint_url: http://ifrs:4566
      s3_access_key_id: test
      s3_secret_access_key: test
service_instance_id: "001"
kafka_servers: ["kafka:9092"]
files_to_register_topic: file-interrogations
files_to_stage_topic: file-downloads
files_to_delete_topic: file-deletions
file_registered_event_topic: internal-file-registry
file_registered_event_type: file_registered
file_staged_event_topic: internal-file-registry
file_staged_event_type: file_staged_for_download
file_deleted_event_topic: internal-file-registry
file_deleted_event_type: file_deleted
db_version_collection: ifrsDbVersions
migration_wait_sec: 10
