ekss_base_url: http://ekss:8080/
kafka_servers: ["kafka:9092"]
service_instance_id: "001"

object_storages:
  test:
    bucket: staging
    credentials:
      s3_endpoint_url: http://irs:4566
      s3_access_key_id: test
      s3_secret_access_key: test

file_registered_event_topic: internal-file-registry
file_upload_validation_success_topic: file-upload-validation-success
file_registered_event_type: file_registered
interrogation_topic: file-interrogations
interrogation_failure_type: file_validation_failed
upload_received_event_topic: uploads

object_stale_after_minutes: 1440

db_connection_str: "mongodb://mongodb:27017"
db_name: "dev_db"
