ekss_base_url: http://ekss:8080/
kafka_servers: ["kafka:9092"]
kafka_enable_dlq: True
service_instance_id: "001"

object_storages:
  test:
    bucket: staging
    credentials:
      s3_endpoint_url: http://irs:4566
      s3_access_key_id: test
      s3_secret_access_key: test

file_internally_registered_topic: internal-file-registry
file_internally_registered_type: file_registered
file_interrogations_topic: file-interrogations
interrogation_success_type: file_interrogation_success
interrogation_failure_type: file_interrogation_failure
file_upload_received_topic: uploads
file_upload_received_type: file_upload_received

object_stale_after_minutes: 1440

mongo_dsn: "mongodb://mongodb:27017"
db_name: "dev"
