db_name: dev
ekss_base_url: http://ekss:8080/
file_registered_event_topic: internal-file-registry
file_registered_event_type: file_registered
file_upload_validation_success_topic: file-upload-validation-success
file_validations_collection: fileValidations
generate_correlation_id: true
interrogation_failure_type: file_validation_failed
interrogation_topic: file-interrogations
kafka_dlq_topic: dlq
kafka_enable_dlq: true
kafka_max_message_size: 1048576
kafka_max_retries: 0
kafka_retry_backoff: 0
kafka_security_protocol: PLAINTEXT
kafka_servers:
- kafka:9092
kafka_ssl_cafile: ''
kafka_ssl_certfile: ''
kafka_ssl_keyfile: ''
kafka_ssl_password: ''
log_format: null
log_level: INFO
log_traceback: true
mongo_dsn: '**********'
mongo_timeout: null
object_stale_after_minutes: 1440
object_storages:
  test:
    bucket: staging
    credentials:
      aws_config_ini: null
      s3_access_key_id: test
      s3_endpoint_url: http://irs:4566
      s3_secret_access_key: '**********'
      s3_session_token: null
service_instance_id: '001'
service_name: irs
upload_received_event_topic: uploads
