[project]
name = "pcs"
version = "1.2.0"
description = "Purge Controller Service - a service to commission file deletions"

[project.urls]
Repository = "https://github.com/ghga-de/pcs"

[project.scripts]
pcs = "pcs.__main__:cli"
