host: 127.0.0.1
port: 8080
workers: 1
auto_reload: true
cors_allowed_origins: []
cors_allow_credentials: False
cors_allowed_methods: []
cors_allowed_headers: []

drs_server_uri: drs://localhost:8080/
api_route: /ga4gh/drs/v1

presigned_url_expires_after: 30

object_storages:
  test:
    bucket: outbox
    credentials:
      s3_endpoint_url: http://dcs:4566
      s3_access_key_id: test
      s3_secret_access_key: test

db_connection_str: "mongodb://mongodb:27017"
db_name: "dev_db"

ekss_base_url: http://ekss:8080/

service_instance_id: "001"
kafka_servers: ["kafka:9092"]

download_served_event_topic: file_downloads
download_served_event_type: donwload_served
file_registered_event_topic: file_downloads
file_registered_event_type: file_registered
files_to_register_topic: internal_file_registry
files_to_register_type: file_registered
unstaged_download_event_topic: file_downloads
unstaged_download_event_type: unstaged_download_requested
files_to_delete_topic: file_deletions
files_to_delete_type: file_deletion_requested
file_deleted_event_topic: file_downloads
file_deleted_event_type: file_deleted
auth_key: "{}"
log_level: INFO
