db_connection_str: "mongodb://mongodb:27017"
db_name: "dev"
object_storages:
  test:
    bucket: inbox
    credentials:
      s3_endpoint_url: http://ucs:4566
      s3_access_key_id: test
      s3_secret_access_key: test
files_to_delete_topic: file-deletions
file_deleted_event_topic: file-downloads
file_deleted_event_type: file_deleted
file_metadata_event_topic: metadata
file_metadata_event_type: metadata_upserted
upload_accepted_event_topic: internal-file-registry
upload_accepted_event_type: file_registered
file_upload_received_topic: file-uploads
upload_rejected_event_topic: file-interrogation
upload_rejected_event_type: file_validation_failed
file_upload_received_collection: fileUploads
service_instance_id: "001"
kafka_servers: ["kafka:9092"]
