host: 127.0.0.1
port: 8080
workers: 1
auto_reload: true
cors_allowed_origins: []
cors_allow_credentials: False
cors_allowed_methods: []
cors_allowed_headers: []

drs_server_uri: drs://localhost:8080/
api_route: /ga4gh/drs/v1

presigned_url_expires_after: 30

object_storages:
  test:
    bucket: outbox
    credentials:
      s3_endpoint_url: http://dcs:4566
      s3_access_key_id: test
      s3_secret_access_key: test

mongo_dsn: "mongodb://mongodb:27017"
db_name: "dev"

ekss_base_url: http://ekss:8080/

service_instance_id: "001"
kafka_servers: ["kafka:9092"]
kafka_enable_dlq: True

download_served_topic: file-downloads
download_served_type: download_served
file_registered_for_download_topic: file-downloads
file_registered_for_download_type: file_registered
file_internally_registered_topic: internal-file-registry
file_internally_registered_type: file_registered
files_to_stage_topic: file-downloads
unstaged_download_collection: unstagedDownloadRequested
file_deletion_request_topic: file-deletions
file_deleted_topic: file-downloads
file_deleted_type: file_deleted
db_version_collection: dcsDbVersions
migration_wait_sec: 10
auth_key: "{}"
log_level: INFO
