api_root_path: ''
api_route: /ga4gh/drs/v1
auth_algs:
- ES256
auth_check_claims:
  email: null
  exp: null
  file_id: null
  full_user_name: null
  iat: null
  type: null
  user_id: null
  user_public_crypt4gh_key: null
auth_key: '{}'
auth_map_claims: {}
auto_reload: true
cache_timeout: 7
cors_allow_credentials: false
cors_allowed_headers: []
cors_allowed_methods: []
cors_allowed_origins: []
db_connection_str: '**********'
db_name: dev_db
docs_url: /docs
download_served_event_topic: file_downloads
download_served_event_type: donwload_served
drs_server_uri: drs://localhost:8080/
ekss_base_url: http://ekss:8080/
file_deleted_event_topic: file_downloads
file_deleted_event_type: file_deleted
file_registered_event_topic: file_downloads
file_registered_event_type: file_registered
files_to_delete_topic: file_deletions
files_to_delete_type: file_deletion_requested
files_to_register_topic: internal_file_registry
files_to_register_type: file_registered
generate_correlation_id: true
host: 127.0.0.1
kafka_security_protocol: PLAINTEXT
kafka_servers:
- kafka:9092
kafka_ssl_cafile: ''
kafka_ssl_certfile: ''
kafka_ssl_keyfile: ''
kafka_ssl_password: ''
log_format: null
log_level: INFO
object_storages:
  test:
    bucket: outbox
    credentials:
      aws_config_ini: null
      s3_access_key_id: test
      s3_endpoint_url: http://dcs:4566
      s3_secret_access_key: '**********'
      s3_session_token: null
openapi_url: /openapi.json
port: 8080
presigned_url_expires_after: 30
retry_access_after: 120
service_instance_id: '001'
service_name: dcs
unstaged_download_event_topic: file_downloads
unstaged_download_event_type: unstaged_download_requested
workers: 1
