#!/bin/bash
# install service in dev container

cd /workspace

# upgrade pip
python -m pip install --upgrade pip

# install or upgrade dependencies for development and testing
pip install --no-deps -r ./lock/requirements-dev.txt

# install the package itself in edit mode:
for dir in ./services/*; do
    pip install --no-deps -e $dir
done


# install pre-commit hooks to git
pre-commit install
