#!/bin/bash
# install service in dev container

cd /workspace

# upgrade pip
python -m pip install --upgrade pip

# install global depencies for all services
pip install --no-deps -r ./lock/requirements-dev.txt

# install services as packages in edit mode:
for dir in ./services/*; do
    pip install --no-deps -e $dir
done


# install pre-commit hooks to git
pre-commit install
