service_name: fins

service_instance_id: '1'
kafka_servers: ["kafka:9092"]

db_connection_str: "mongodb://mongodb:27017"
db_name: "dev"

files_to_delete_topic: file-deletions
file_registered_event_topic: internal-file-registry
file_registered_event_type: file_registered
