service_name: fins

service_instance_id: '1'
kafka_servers: ["kafka:9092"]

db_connection_str: "mongodb://mongodb:27017"
db_name: "dev_db"

files_to_delete_topic: file_deletions
file_registered_event_topic: internal_file_registry
file_registered_event_type: file_registered
