components:
  schemas:
    FileInformation:
      description: 'Basic public information container for files registered with the
        Internal File

        Registry service.'
      properties:
        file_id:
          description: Public identifier of the file associated with the given information
          title: File Id
          type: string
        sha256_hash:
          description: SHA256 hash of the unencrypted file content encoded as hexadecimal  values
            as produced by hashlib.hexdigest().
          title: Sha256 Hash
          type: string
        size:
          description: Size of the unencrypted file in bytes.
          exclusiveMinimum: 0.0
          title: Size
          type: integer
      required:
      - file_id
      - size
      - sha256_hash
      title: FileInformation
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    HttpInformationNotFoundError:
      additionalProperties: false
      properties:
        data:
          $ref: '#/components/schemas/HttpInformationNotFoundErrorData'
        description:
          description: A human readable message to the client explaining the cause
            of the exception.
          title: Description
          type: string
        exception_id:
          const: informationNotFound
          enum:
          - informationNotFound
          title: Exception Id
          type: string
      required:
      - data
      - description
      - exception_id
      title: HttpInformationNotFoundError
      type: object
    HttpInformationNotFoundErrorData:
      properties:
        file_id:
          title: File Id
          type: string
      required:
      - file_id
      title: HttpInformationNotFoundErrorData
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  description: Providing public metadata about files registered with the Internal
    File Registry
  title: File Information Service
  version: 1.0.1
openapi: 3.1.0
paths:
  /file_information/{file_id}:
    get:
      description: Retrieve and serve stored file information.
      operationId: getFileInformation
      parameters:
      - in: path
        name: file_id
        required: true
        schema:
          title: File Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileInformation'
          description: A configuration or external communication error has occurred
            and details should not be communicated to the client
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpInformationNotFoundError'
          description: 'Exceptions by ID:

            - informationNotFound: No information registered for the given ID.'
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Return public file information for the given file id, i.e. public accession.
      tags:
      - FileIngestService
  /health:
    get:
      description: Used to test if this service is alive
      operationId: health_health_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: health
      tags:
      - FileIngestService
tags:
- name: FileInformationService
