[project]
name = "irs"
version = "2.1.0"
description = "Interrogation Room Service"

[project.urls]
Repository = "https://github.com/ghga-de/interrogation-room-service"

[project.scripts]
irs = "irs.__main__:cli"
