"""additional fields

Revision ID: b66ee07d83b5
Revises: dda104bd723f
Create Date: 2022-01-18 13:04:25.537622

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b66ee07d83b5"
down_revision = "dda104bd723f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drs_objects", sa.Column("creation_date", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "drs_objects", sa.Column("update_date", sa.DateTime(), nullable=False)
    )
    op.add_column("drs_objects", sa.Column("format", sa.String(), nullable=False))
    op.drop_column("drs_objects", "registration_date")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drs_objects",
        sa.Column(
            "registration_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("drs_objects", "format")
    op.drop_column("drs_objects", "update_date")
    op.drop_column("drs_objects", "creation_date")
    # ### end Alembic commands ###
