# Copyright 2022-2024 Universität Tübingen, DKFZ and EMBL
# for the German Human Genome-Phenome Archive (GHGA)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Check if OpenAPI spec is up to date

on: push

env:
  PYTHON_VERSION: '3.9'
  IFRS_CONFIG_YAML: ./services/ifrs/dev_config.yaml
  IRS_CONFIG_YAML: ./services/irs/dev_config.yaml
  PCS_CONFIG_YAML: ./services/pcs/dev_config.yaml

jobs:
  build-cache:
    uses: ./.github/workflows/prepare_build_cache.yaml
    with:
      cache-key: ${{ github.sha }}

  check-openapi-specs:
    name: Check config schema and example
    needs: build-cache
    if: ${{ needs.build-cache.outputs.services != '' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ${{ fromJson(needs.build-cache.outputs.services) }}
      fail-fast: false

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Restore cache
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.repository }}
            ${{ env.pythonLocation }}
          key: ${{ github.sha }}

      - name: Check openapi.yaml
        id: check-openapi-docs
        run: |
          python3 ./scripts/update_openapi_docs.py --check ${{matrix.service}}
