name: Check if the config schema and the example are up to date

on: push

jobs:
  get-changed-services:
    uses: ./.github/workflows/get_affected_services.yaml

  check-config:
    name: Check config schema and example
    needs: get-changed-services
    if: ${{ needs.get-changed-services.outputs.since-last-commit != '' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ${{ fromJson(needs.get-changed-services.outputs.since-last-commit) }}
      fail-fast: false

    env:
      IFRS_CONFIG_YAML: ./services/ifrs/dev_config.yaml
      IRS_CONFIG_YAML: ./services/irs/dev_config.yaml
      PCS_CONFIG_YAML: ./services/pcs/dev_config.yaml

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Update pip and install dependencies
        id: install-dependencies
        run: python -m pip install --upgrade pip && pip install --no-deps -r ./lock/requirements-dev.txt && pip install --no-deps ./services/${{matrix.service}}

      - name: Check config docs
        id: check-config-docs
        run: |
          python3 ./scripts/update_config_docs.py --check ${{matrix.service}}
