name: Get services affected by changes

on:
  workflow_call:
    outputs:
      services:
        description: "Services affected by changes since last commit"
        value: ${{ jobs.get-changed-services.outputs.services }}

jobs:
  get-changed-services:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.services-changed.outputs.affected }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python 3.12
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Install Typer to check changed services
        id: install-typer
        run: pip install typer>=0.9.0

      - name: Generate list of changed services
        id: services-changed
        run: |
          echo "affected=$(python3 ./scripts/get_affected_services.py ${{ steps.changed-files.outputs.all_changed_files }} )" >> $GITHUB_OUTPUT
