name: Monorepo Tests

on: push

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.affected }}
    steps:
      - uses: actions/checkout@v3

      - id: install-typer
        run: pip install typer>=0.9.0

      - id: set-matrix
        run: |
          echo "affected=$(python3 ./scripts/affected_services.py)" >> $GITHUB_OUTPUT

  test:
    needs: check-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.check-changes.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github
            .lock
            .services/${{matrix.service}}

      - name: setup
        run: pip install --no-deps -r ./lock/requirements-dev.txt && pip install --upgrade ./services/${{matrix.service}}/

      - name: run tests for specific service
        run: pytest ./services/${{matrix.service}}/
