name: Run tests on non main branch

on:
  push:
    branches-ignore:
      - main

env:
  IFRS_CONFIG_YAML: ./services/ifrs/dev_config.yaml
  IRS_CONFIG_YAML: ./services/irs/dev_config.yaml
  PCS_CONFIG_YAML: ./services/pcs/dev_config.yaml
  UCS_CONFIG_YAML: ./services/ucs/dev_config.yaml
  DCS_CONFIG_YAML: ./services/dcs/dev_config.yaml
  EKSS_CONFIG_YAML: ./services/ekss/dev_config.yaml
  FIS_CONFIG_YAML: ./services/fis/dev_config.yaml

jobs:
  get-changed-services:
    uses: ./.github/workflows/get_affected_services.yaml

  test:
    needs: get-changed-services
    if: ${{ needs.get-changed-services.outputs.services != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.get-changed-services.outputs.services) }}
      fail-fast: false

    steps:
      - name: Checkout ${{matrix.service}}
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python 3.12
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Update pip and pyopenssl
        id: pip-update
        run: python -m pip install --upgrade pip && pip install --upgrade pyopenssl

      - name: Install global and local dependencies for ${{matrix.service}}
        id: install-dependencies
        run: pip install --no-deps -r ./lock/requirements-dev.txt && pip install --no-deps ./services/${{matrix.service}}

      - name: Run tests for ${{matrix.service}}
        id: run-tests
        run: pytest ./services/${{matrix.service}}
