# Copyright 2022-2024 Universität Tübingen, DKFZ and EMBL
# for the German Human Genome-Phenome Archive (GHGA)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Static Code Analysis

on: push

env:
  PYTHON_VERSION: '3.9'

jobs:
  build-cache:
    uses: ./.github/workflows/prepare_build_cache.yaml
    with:
      cache-key: ${{ github.sha }}

  static-code-analysis:
    name: Static Code Analysis
    needs: build-cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Restore cache
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.repository }}
            ${{ env.pythonLocation }}
          key: ${{ github.sha }}


      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch

      - name: Run ruff
        id: ruff
        run: |
          ruff check --output-format=github .
          ruff format --check .

      - name: Run mypy
        id: mypy
        run: |
          mypy .

      - name: Check license header and file
        id: license-checker
        run: |
          ./scripts/check_license.py
