name: Monorepo Push Tests

on:
  push:
    branches-ignore:
      - main

jobs:
  get-changed-services:
    uses: ./.github/workflows/get_affected_services.yaml

  test:
    needs: get-changed-services
    if: ${{ needs.get-changed-services.outputs.since-last-commit != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.get-changed-services.outputs.since-last-commit) }}
      fail-fast: false
    env:
      IFRS_CONFIG_YAML: ./services/ifrs/dev_config.yaml
      IRS_CONFIG_YAML: ./services/irs/dev_config.yaml
      PCS_CONFIG_YAML: ./services/pcs/dev_config.yaml
    steps:
      - name: Checkout ${{matrix.service}}
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Update pip and pyopenssl
        id: pip-update
        run: python -m pip install --upgrade pip && pip install --upgrade pyopenssl

      - name: Install global and local dependencies for ${{matrix.service}}
        id: install-dependencies
        run: pip install --no-deps -r ./lock/requirements-dev.txt && pip install --no-deps ./services/${{matrix.service}}

      - name: Run tests for ${{matrix.service}}
        id: run-tests
        run: pytest ./services/${{matrix.service}}
